version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    volumes:
      - ./client:/home/node/app
      - ./client/node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    command: yarn install

  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    volumes:
      - ./server:/home/node/app
      - ./server/node_modules:/home/node/app/node_modules
    ports:
      - "3001:3001"
    command: yarn install
